# Generated by Django 4.2.16 on 2024-10-29 01:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city_name', models.CharField(db_index=True, max_length=80, verbose_name='Name')),
                ('short_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Short Name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['city_name'],
            },
        ),
    ]
