# Generated by Django 4.2.16 on 2024-09-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['short_name'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['city_name'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
        migrations.AddField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(db_index=True, default=10, max_length=80, verbose_name='neighborhood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='postal_number',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(db_index=True, default='o', max_length=80, verbose_name='street'),
            preserve_default=False,
        ),
    ]
